export const cats = [
  {
    id: "cat-1",
    name: "SNOWBALL",
    color: "White",
    personality: "The Cuddle Bug",
    labelColor: "var(--accent-yellow)",
    borderColor: "var(--text-secondary)",
    image: "/images/persian_cat_hero_1781632106586.png",
    status: "Available",
    price: 1200,
    featured: true,
    description: "Snowball is an absolute sweetheart. She loves to curl up on your lap and purr for hours. A perfect companion for quiet evenings."
  },
  {
    id: "cat-2",
    name: "PUMPKIN",
    color: "Ginger",
    personality: "The Explorer",
    labelColor: "var(--accent-blue)",
    borderColor: "var(--accent-blue)",
    image: "/images/persian_cat_card1_1781632116193.png",
    status: "Available",
    price: 1500,
    featured: true,
    description: "Pumpkin is a curious and playful ginger kitten. He loves investigating new toys and chasing laser pointers around the house."
  },
  {
    id: "cat-3",
    name: "SMOKEY",
    color: "Grey",
    personality: "The Sleepyhead",
    labelColor: "#8bc34a",
    borderColor: "var(--accent-yellow)",
    image: "/images/persian_cat_card2_1781632132566.png",
    status: "Reserved",
    price: 1300,
    featured: false,
    description: "Smokey is a calm and gentle grey Persian. He spends most of his day napping in sunny spots. He's very docile and sweet."
  },
  {
    id: "cat-4",
    name: "LUNA",
    color: "White",
    personality: "The Princess",
    labelColor: "var(--accent-yellow)",
    borderColor: "var(--text-secondary)",
    image: "/images/hero_cat_center_1781632442304.png",
    status: "Available",
    price: 1800,
    featured: false,
    description: "Luna is royalty and she knows it. With her pristine white coat and bright eyes, she loves being pampered and groomed."
  },
  {
    id: "cat-5",
    name: "GARFIELD",
    color: "Ginger",
    personality: "The Foodie",
    labelColor: "var(--accent-blue)",
    borderColor: "var(--accent-blue)",
    image: "/images/hero_cat_left_1781632453260.png",
    status: "Available",
    price: 1400,
    featured: false,
    description: "Garfield is always first in line for meals. He is extremely affectionate, especially when you are holding a bag of treats."
  },
  {
    id: "cat-6",
    name: "ASH",
    color: "Grey",
    personality: "The Ninja",
    labelColor: "#8bc34a",
    borderColor: "var(--accent-yellow)",
    image: "/images/hero_cat_right_1781632465440.png",
    status: "Available",
    price: 1350,
    featured: false,
    description: "Ash is energetic and sneaky. He loves to playfully pounce from behind couches. Great for active families!"
  },
  {
    id: "cat-7",
    name: "BELLA",
    color: "White",
    personality: "The Diva",
    labelColor: "var(--accent-yellow)",
    borderColor: "var(--text-secondary)",
    image: "/images/persian_cat_hero_1781632106586.png",
    status: "Available",
    price: 1600,
    featured: false,
    description: "Bella expects nothing but the best. She loves being brushed and looking glamorous at all times."
  },
  {
    id: "cat-8",
    name: "MILO",
    color: "Ginger",
    personality: "The Acrobat",
    labelColor: "var(--accent-blue)",
    borderColor: "var(--accent-blue)",
    image: "/images/persian_cat_card1_1781632116193.png",
    status: "Available",
    price: 1250,
    featured: false,
    description: "Milo is an energetic jumper. He loves exploring the highest shelves in the house and chasing feather toys."
  },
  {
    id: "cat-9",
    name: "OLIVER",
    color: "Grey",
    personality: "The Thinker",
    labelColor: "#8bc34a",
    borderColor: "var(--accent-yellow)",
    image: "/images/persian_cat_card2_1781632132566.png",
    status: "Available",
    price: 1450,
    featured: false,
    description: "Oliver is a quiet and observant kitten. He loves to sit by the window and watch the birds for hours."
  },
  {
    id: "cat-10",
    name: "LEO",
    color: "Ginger",
    personality: "The Lion",
    labelColor: "var(--accent-blue)",
    borderColor: "var(--accent-blue)",
    image: "/images/hero_cat_left_1781632453260.png",
    status: "Reserved",
    price: 1550,
    featured: false,
    description: "Leo has a big personality. He is brave, bold, and loves to be the center of attention in any room."
  },
  {
    id: "cat-11",
    name: "SIMBA",
    color: "Grey",
    personality: "The Shadow",
    labelColor: "#8bc34a",
    borderColor: "var(--accent-yellow)",
    image: "/images/hero_cat_right_1781632465440.png",
    status: "Available",
    price: 1350,
    featured: false,
    description: "Simba will follow you everywhere. If you are looking for a constant companion, he is your guy."
  },
  {
    id: "cat-12",
    name: "CHLOE",
    color: "White",
    personality: "The Snuggler",
    labelColor: "var(--accent-yellow)",
    borderColor: "var(--text-secondary)",
    image: "/images/hero_cat_center_1781632442304.png",
    status: "Available",
    price: 1700,
    featured: false,
    description: "Chloe just wants to be held. She has the softest purr and will gladly sleep on your chest."
  },
  {
    id: "cat-13",
    name: "NALA",
    color: "Ginger",
    personality: "The Hunter",
    labelColor: "var(--accent-blue)",
    borderColor: "var(--accent-blue)",
    image: "/images/persian_cat_card1_1781632116193.png",
    status: "Available",
    price: 1400,
    featured: false,
    description: "Nala is playful and highly alert. She loves to stalk toy mice and has incredibly fast reflexes."
  },
  {
    id: "cat-14",
    name: "MAX",
    color: "Grey",
    personality: "The Boss",
    labelColor: "#8bc34a",
    borderColor: "var(--accent-yellow)",
    image: "/images/persian_cat_card2_1781632132566.png",
    status: "Reserved",
    price: 1650,
    featured: false,
    description: "Max likes to be in charge. He will let you know exactly when it is dinner time with his demanding meows."
  },
  {
    id: "cat-15",
    name: "CHARLIE",
    color: "White",
    personality: "The Artist",
    labelColor: "var(--accent-yellow)",
    borderColor: "var(--text-secondary)",
    image: "/images/persian_cat_hero_1781632106586.png",
    status: "Available",
    price: 1900,
    featured: false,
    description: "Charlie is very delicate and graceful. He navigates around breakable objects like a true professional."
  },
  {
    id: "cat-16",
    name: "LILY",
    color: "White",
    personality: "The Sweetheart",
    labelColor: "var(--accent-yellow)",
    borderColor: "var(--text-secondary)",
    image: "/images/hero_cat_center_1781632442304.png",
    status: "Available",
    price: 1750,
    featured: false,
    description: "Lily is the gentlest kitten you will ever meet. She is very patient, loving, and great with children."
  }
];
